### PR TITLE
More debs

### PR DESCRIPTION
**Pull request by jepler**

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
Looks good to me.  The bullseye amd64 deb installs fine on my laptop.   :+1:

**Comment by SebKuzminsky** [comment]
And the buster armhf deb installs and runs on a raspbian pi here.

**Comment by jepler** [comment]
I added another commit to make one artifact per os+cpu combination.

**Comment by SebKuzminsky** [comment]
I think split artifacts is a good idea - less to download and sort through when all you want is the deb for your machine, and plus the orig tarball is shared among the CPUs of each OS, and could potentially be corrupted if multiple jobs try to write it at the same time.

**Pull request merged**
