### PR TITLE
Make PCI & EPP support conditional

### LINKED ISSUE #42: Makefile update to build on Raspberry Pi
The current Makefile provides partial support for the sys/io.h stubs implementation, missing is an obvious way to enable it.

Please update the Makefile with the following:

   #enable for sys/io.h stubs implementation
   #USE_STUBS = 1

A Raspberry Pi build note in the README.md file:

    To build on a Raspberry Pi:
       Edit the Makefile to enable for sys/io.h stubs implementation.

### PR DESCRIPTION
**Pull request by jepler**
This is intended to resolve #42 by conditionally compiling out the PCI & EPP access methods, which need iopl/inX/outX.  As a part of this, it can remove the io.h "stubs".

### CODE REVIEW

**Comment by jepler** [comment]
@llamatrails can you check whether this lets you get a clean compile on aarch64?

**Comment by llamatrails** [comment]
> @llamatrails can you check whether this lets you get a clean compile on aarch64?

Be happy to, but don't know how to get a patch file for all of this without typing it all in as copy/paste is not getting the plus/minus markers.  Sigh.  Must be an easier way.

**Comment by llamatrails** [comment]
Ok, figured out how to run git on your conditional branch.

Still looking for sys/io.h ...

pi@raspi4:~/Downloads/mesaflash-conditional-pci-epp $ make
gcc -O0 -g -Wall -Werror=format -Werror=format-security -std=c99 -D_GNU_SOURCE  -DMESAFLASH_IO=0 -c eeprom_local.c
eeprom_local.c:20:10: fatal error: sys/io.h: No such file or directory
 #include <sys/io.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:130: eeprom_local.o] Error 1

**Comment by llamatrails** [comment]
Ok, your conditional-pci-epp branch compiles and runs on my 64bit Raspberry Pi 4 4gb.  It talks to my 7c81.

Thanks !!!!

**Comment by jepler** [comment]
Thank you so much for the testing!

**Pull request merged**
